/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage.main.java.com.Apps.View.MenuSideBar;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import newpackage.main.java.com.Apps.Controller.ControllerDatabase.CRUD.data_Barang;
import newpackage.main.java.com.Apps.Controller.ControllerDatabase.tbl_BarangMasuk;
import newpackage.main.java.com.Apps.View.FromView.Form_BarangMasukV2;
import rojerusan.RSMetroTextPlaceHolder;

/**
 *
 * @author ZRF
 */
public class BarangMasuk extends javax.swing.JPanel {
    tbl_BarangMasuk tbl = new tbl_BarangMasuk();
    Form_BarangMasukV2 form = new Form_BarangMasukV2();
    data_Barang data = new data_Barang(); 
    /**
     * Creates new form BarangMasuk
     */
    public BarangMasuk() {
        initComponents();
        tbl.tableBarangKeluar(this);
        customizeTableHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_main = new javax.swing.JPanel();
        jPanel2 = new RoundedPanel(15);
        jLabel1 = new javax.swing.JLabel();
        jSrcBarang = new rojerusan.RSMetroTextPlaceHolder();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarangMasuk = new javax.swing.JTable();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();

        setLayout(new java.awt.BorderLayout());

        p_main.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Data Barang Masuk");

        rSMaterialButtonRectangle2.setText("Cari");
        rSMaterialButtonRectangle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSrcBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSrcBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblBarangMasuk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblBarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Barang Masuk", "Kode Barang", "Nama Barang", "Tanggal Masuk", "Jumlah Barang Masuk", "Kode Supplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBarangMasuk.setRowHeight(30);
        jScrollPane1.setViewportView(tblBarangMasuk);
        if (tblBarangMasuk.getColumnModel().getColumnCount() > 0) {
            tblBarangMasuk.getColumnModel().getColumn(0).setMinWidth(30);
            tblBarangMasuk.getColumnModel().getColumn(0).setMaxWidth(40);
            tblBarangMasuk.getColumnModel().getColumn(2).setMinWidth(150);
            tblBarangMasuk.getColumnModel().getColumn(2).setMaxWidth(300);
            tblBarangMasuk.getColumnModel().getColumn(4).setMinWidth(150);
            tblBarangMasuk.getColumnModel().getColumn(4).setMaxWidth(400);
        }

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(51, 153, 255));
        rSMaterialButtonRectangle1.setText("Tambah Barang Masuk");
        rSMaterialButtonRectangle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE))
                .addContainerGap())
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        add(p_main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1MouseClicked
       form.setVisible(true);
    }//GEN-LAST:event_rSMaterialButtonRectangle1MouseClicked

    private void rSMaterialButtonRectangle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2MouseClicked
       data.searchignBarangMasuk(this);
    }//GEN-LAST:event_rSMaterialButtonRectangle2MouseClicked

    public JTable getTblBarangMasuk() {
        return tblBarangMasuk;
    }

    public void setTblBarangMasuk(JTable tblBarangMasuk) {
        this.tblBarangMasuk = tblBarangMasuk;
    }
public class RoundedPanel extends JPanel {
    
    private int cornerRadius;

    public RoundedPanel(int cornerRadius) {
        this.cornerRadius = cornerRadius;
        setOpaque(false); // To make sure the panel is transparent and shows rounded corners
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;

        // Anti-aliasing for smoother edges
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Draw the rounded rectangle
        g2d.setColor(getBackground()); // Use the panel's background color
        g2d.fillRoundRect(0, 0, getWidth(), getHeight(), cornerRadius, cornerRadius);
    }

    public int getCornerRadius() {
        return cornerRadius;
    }

    public void setCornerRadius(int cornerRadius) {
        this.cornerRadius = cornerRadius;
        repaint(); // Repaint the panel to reflect the changes
    }
}
    private void customizeTableHeader() {
        // Ambil JTableHeader dari JTable
        JTableHeader tableHeader = tblBarangMasuk.getTableHeader();
        
        // Buat font baru dengan ukuran yang diinginkan
        Font headerFont = new Font("Serif", Font.BOLD, 20); // Sesuaikan dengan kebutuhan
        
        // Set font ke header
        tableHeader.setFont(headerFont);
    }

    public RSMetroTextPlaceHolder getjSrcBarang() {
        return jSrcBarang;
    }

    public void setjSrcBarang(RSMetroTextPlaceHolder jSrcBarang) {
        this.jSrcBarang = jSrcBarang;
    }

    public JPanel getP_main() {
        return p_main;
    }

    public void setP_main(JPanel p_main) {
        this.p_main = p_main;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMetroTextPlaceHolder jSrcBarang;
    private javax.swing.JPanel p_main;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private javax.swing.JTable tblBarangMasuk;
    // End of variables declaration//GEN-END:variables
}
